#!/bin/python3
import socket
HOST= "127.0.0.1"
PORT=7777
s= socket.socket(socket.AF_INET,socket.SOCK_STREAM) #socket.AF_INET for Host, socket.SOCK_STREAM
s.connect(HOST,PORT) #To Connect by host and port
